development:
  clients:
    default:
      database: perpro_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: perpro_test
      hosts:
        - localhost:27017
